name: Daily Run
on:
  # schedule:
  #  - cron: '15 4,10,22 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: execute shell script
        run: |
          sh curl.sh
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: pip install telethon
      - name: execute python script
        run: |
          python python.py
