name: JD Daily Run
on:
  schedule:
    - cron: '15 10,22 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: install node modules
        run: npm install request
      - name: execute JD_DailyBonus script
        run: node JD_DailyBonus.js "${{ secrets.JD_COOKIE }}"
